### ISSUE TITLE
Encrypt doesn't work

### ISSUE THREAD

**Issue by Skyost** [extraStatic/stapsher#3]
Hi,

Encrypting strings doesn't work (ex : https://stapsher.extrastatic.xyz/encrypt/test), a `ERR_CONNECTION_TIMED_OUT` occurs.

**Comment by MunifTanjim** [comment]
Well, it's not a software issue.

It's hosted on a really cheap server and it is down :roll_eyes: Can't do anything about that.

**Comment by Skyost** [comment]
Ow okay. And would it be possible for you to provide us a guide to self-host the software then ?

**Comment by MunifTanjim** [comment]
To be honest, `stapsher` repo is not maintained currently. So, I can't guaranty that everything will work.

And you'll probably have to wait for quite a bit before I can manage the time to write the self-hosting guide.

Instead, I'll suggest to look at [Staticman](https://github.com/eduardoboucas/staticman). Currently, Staticman can do everything that Stapsher does and more on top of that. Also, it has a really good community backing and is well maintained.

**Comment by Skyost** [comment]
Thank you !
